name: The Node & Redis Project

on: 
  push:
    branches: [master]

jobs:  
  build-test: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    env:
      PORT: 4001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install 

      - name: Run Tests
        run: echo "Running Tests"

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: Running The Container
        run: docker run -d -p 4001:8080 myapp  # Added -d to run in background

      - name: Active-Container Display
        run: docker ps
